spring:
  application:
    name: sb-hotel

  datasource:
    url: "jdbc:h2:mem:hotel"
    driver-class-name: org.h2.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        hbm2ddl: create-drop
